name: Wine-Crossover-26-MacOS

on:
  workflow_dispatch:

env:
    MACOSX_DEPLOYMENT_TARGET: 10.14
    WINE_CONFIGURE: ${{ github.workspace }}/sources/wine/configure
    BUILDROOT: ${{ github.workspace }}/build
    INSTALLROOT: ${{ github.workspace }}/install
    CROSS_OVER_VERSION: 26.2.0
    CROSS_OVER_SOURCE_URL: https://media.codeweavers.com/pub/crossover/source/crossover-sources-26.2.0.tar.gz
    CROSS_OVER_LOCAL_FILE: crossover-26.2.0
    WINE_INSTALLATION: wine-cx26.2.0
    MOLTENVK_DXVK_INSTALLATION: moltenvk-dxvk

jobs:
  moltenVK_DXVK:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore MoltenVK / DXVK from cache
        uses: actions/cache@v4
        id: cache_moltenVK_DXVK
        with:
          path: ${{ env.INSTALLROOT }}/${{ env.MOLTENVK_DXVK_INSTALLATION }}
          key: cache_moltenVK_DXVK_cx26_v1

      - name: Get and Extract Source
        if: steps.cache_moltenVK_DXVK.outputs.cache-hit != 'true'
        uses: ./.github/actions/get_source
        with:
          crossover-local-file: "${{ env.CROSS_OVER_LOCAL_FILE }}"
          crossover-source-url: "${{ env.CROSS_OVER_SOURCE_URL }}"

      - name: Set up Python 3.11
        if: steps.cache_moltenVK_DXVK.outputs.cache-hit != 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build MoltenVK
        if: steps.cache_moltenVK_DXVK.outputs.cache-hit != 'true'
        run: |
          pushd sources/moltenvk
          ./fetchDependencies --macos
          make macos
          popd

      - name: Install MoltenVK
        if: steps.cache_moltenVK_DXVK.outputs.cache-hit != 'true'
        run: |
          set -x
          pushd sources/moltenvk/Package/Latest/MoltenVK
          mkdir -p ${{ env.INSTALLROOT }}/${{ env.MOLTENVK_DXVK_INSTALLATION }}/usr/local/lib/
          cp ./dylib/macOS/*.dylib ${{ env.INSTALLROOT }}/${{ env.MOLTENVK_DXVK_INSTALLATION }}/usr/local/lib/
          cp -r ./include ${{ env.INSTALLROOT }}/${{ env.MOLTENVK_DXVK_INSTALLATION }}/usr/local/
          popd
          pushd sources/moltenvk/External/glslang/External/spirv-tools/external/spirv-headers/include/
          cp -r ./spirv ${{ env.INSTALLROOT }}/${{ env.MOLTENVK_DXVK_INSTALLATION }}/usr/local/include/
          popd

      - name: Install DXVK Dependencies
        if: steps.cache_moltenVK_DXVK.outputs.cache-hit != 'true'
        run: |
          brew update
          brew install glslang mingw-w64 meson

      - name: Build DXVK
        if: steps.cache_moltenVK_DXVK.outputs.cache-hit != 'true'
        run: |
          set -x
          pushd sources/dxvk
          ./package-release.sh master sources/dxvk/install --no-package
          popd

      - name: Install DXVK
        if: steps.cache_moltenVK_DXVK.outputs.cache-hit != 'true'
        run: |
          set -x
          pushd sources/dxvk/install/dxvk-macOS-master
          mkdir -p ${{ env.INSTALLROOT }}/${{ env.MOLTENVK_DXVK_INSTALLATION }}/usr/local/lib64/wine
          cp -r x64 ${{ env.INSTALLROOT }}/${{ env.MOLTENVK_DXVK_INSTALLATION }}/usr/local/lib64/wine/dxvk
          mkdir -p ${{ env.INSTALLROOT }}/${{ env.MOLTENVK_DXVK_INSTALLATION }}/usr/local/bin
          cp setup_dxvk.sh ${{ env.INSTALLROOT }}/${{ env.MOLTENVK_DXVK_INSTALLATION }}/usr/local/bin/
          popd

      - name: Tar MoltenVK / DXVK
        run: |
          set -x
          pushd ${{ env.INSTALLROOT }}
          tar -czf ${{ env.MOLTENVK_DXVK_INSTALLATION }}.tar.gz ${{ env.MOLTENVK_DXVK_INSTALLATION }}
          popd

      - name: Upload MoltenVK / DXVK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.MOLTENVK_DXVK_INSTALLATION }}
          path: ${{ env.INSTALLROOT }}/${{ env.MOLTENVK_DXVK_INSTALLATION }}.tar.gz

  wine-crossover:
    needs: [moltenVK_DXVK]
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get latest HomeBrew formulas/bottles
        run: brew update

      - name: Install Wine Build Dependencies
        run: |
          brew install  bison              \
                        gcenx/wine/cx-llvm \
                        flex               \
                        mingw-w64          \
                        pkgconfig

      - name: Install Wine Runtime Dependencies
        run: |
          brew install  freetype           \
                        gphoto2            \
                        gst-plugins-base   \
                        krb5               \
                        molten-vk          \
                        sane-backends      \
                        sdl2

      - name: Add bison, cx-llvm, flex & krb5 to $PATH
        run: |
          echo "$(brew --prefix bison)/bin"   >> $GITHUB_PATH
          echo "$(brew --prefix cx-llvm)/bin" >> $GITHUB_PATH
          echo "$(brew --prefix flex)/bin"    >> $GITHUB_PATH
          echo "$(brew --prefix krb5)/bin"    >> $GITHUB_PATH

      - name: Download MoltenVK / DXVK
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.MOLTENVK_DXVK_INSTALLATION }}
          path: ${{ env.INSTALLROOT }}

      - name: Unpack MoltenVK / DXVK
        run: |
          set -x
          mkdir -p ${{ env.INSTALLROOT }}/${{ env.WINE_INSTALLATION }}
          pushd ${{ env.INSTALLROOT }}/${{ env.WINE_INSTALLATION }}
          tar --strip-components=1 -xvf ${{ env.INSTALLROOT }}/${{ env.MOLTENVK_DXVK_INSTALLATION }}.tar.gz
          popd

      - name: Get and Extract Source
        uses: ./.github/actions/get_source
        with:
          crossover-local-file: "${{ env.CROSS_OVER_LOCAL_FILE }}"
          crossover-source-url: "${{ env.CROSS_OVER_SOURCE_URL }}"

      - name: Configure wine64
        uses: ./.github/actions/configure_wine
        with:
          winearch: "wine64"
          build-dir: "${{ env.BUILDROOT }}/wine64"
          crossflags: "-g -O2"
          configure-params: "--enable-win64 --with-vulkan"

      - name: Build wine64
        uses: ./.github/actions/make
        with:
          build-dir: "${{ env.BUILDROOT }}/wine64"

      - name: Configure wine32on64
        uses: ./.github/actions/configure_wine
        with:
          winearch: "wine32on64"
          build-dir: "${{ env.BUILDROOT }}/wine32on64"
          crossflags: "-g -O2"
          configure-params: "--enable-win32on64 --with-wine64=${{ env.BUILDROOT }}/wine64 --without-cms --without-openal --without-gstreamer --without-gphoto --without-krb5 --without-sane --without-vulkan --disable-vulkan_1 --disable-winedbg --disable-winevulkan"

      - name: Build wine32on64
        uses: ./.github/actions/make
        with:
          build-dir: "${{ env.BUILDROOT }}/wine32on64"

      - name: Install wine32on64
        uses: ./.github/actions/install
        with:
          build-dir: "${{ env.BUILDROOT }}/wine32on64"
          install-dir: "${{ env.INSTALLROOT }}/${{ env.WINE_INSTALLATION }}"

      - name: Install wine64
        uses: ./.github/actions/install
        with:
          build-dir: "${{ env.BUILDROOT }}/wine64"
          install-dir: "${{ env.INSTALLROOT }}/${{ env.WINE_INSTALLATION }}"

      - name: Create wine, wine-preloader symlinks
        run: |
          pushd ${{ env.INSTALLROOT }}/${{ env.WINE_INSTALLATION }}/usr/local/bin
          ln -s wine32on64 wine
          ln -s wine32on64-preloader wine-preloader
          popd

      - name: Tar Wine
        run: |
          set -x
          pushd ${{ env.INSTALLROOT }}
          tar -czvf ${{ env.WINE_INSTALLATION }}.tar.gz ${{ env.WINE_INSTALLATION }}
          popd

      - name: Upload Wine
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.WINE_INSTALLATION }}
          path: ${{ env.INSTALLROOT }}/${{ env.WINE_INSTALLATION }}.tar.gz
